name: SmartAdmin
version: 0.1.1-beta
main: cz.betminekdev.smartadmin.SmartAdminPlugin
api-version: "1.21"
author: BetminekDev
description: Smart staff assistant for Minecraft servers.

libraries:
  - org.xerial:sqlite-jdbc:3.53.1.0

commands:
  smartadmin:
    description: Main SmartAdmin staff assistant command
    aliases: [sa, si]
    usage: /smartadmin help

permissions:
  smartadmin.admin:
    description: Full access to SmartAdmin.
    default: op
  smartadmin.staff:
    description: Can use profile, timeline, watch, and alerts commands.
    default: op
  smartadmin.reload:
    description: Can reload SmartAdmin configuration.
    default: op
  smartadmin.alerts:
    description: Can receive SmartAdmin staff alerts.
    default: op
  smartadmin.reset:
    description: Can reset a player's SmartAdmin risk score.
    default: op
  smartadmin.note:
    description: Can add staff notes to a player's SmartAdmin timeline.
    default: op
  smartadmin.bypass:
    description: Excludes a player from risk scoring unless configured otherwise.
    default: false
